name: Check codebase formatting
on: [push, pull_request]

jobs:
  format: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core
        uses: actions/setup-dotnet@v2
        with: 
          dotnet-version: "6.0.x"

      - name: Build solution
        run: dotnet build

      - name: Install dotnet format tool 
        run: dotnet tool update --global dotnet-format

      - name: Perform format check
        run: dotnet format --verify-no-changes --verbosity diagnostic

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x
          cache: npm
          cache-dependency-path: frontend/package.json
      
      - name: npm install 
        run: 
          npm install
        working-directory: frontend

      - name: Check react app formatting
        run: npm run lint && npm run format && npm run lint:style
        working-directory: frontend